FROM docker.bintray.io/jfrog/artifactory-oss:6.5.13

# Download the DB driver into Tomcat's lib

RUN curl -L -o /opt/jfrog/artifactory/tomcat/lib/mysql-connector-java-5.1.41.jar https://jcenter.bintray.com/mysql/mysql-connector-java/5.1.41/mysql-connector-java-5.1.41.jar

